version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "auction-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9zlzllbz5o49"
s3_prefix = "auction-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
