AWSTemplateFormatVersion: 2010-09-09
Description: >-
  auction-service

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
Resources:
  # This is a Lambda function config associated with the source code: getAuctions.js
  getAuctions:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/auction/getAuctions.getAuctions
      FunctionName: getAuctions
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: HTTP get method to get all items from a DynamoDB table.
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AuctionsTable
      Environment:
        Variables:
          AUCTIONS_TABLE_NAME: !Ref AuctionsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /auctions
            Method: GET

  # This is a Lambda function config associated with the source code: getAuction.js
  getAuction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/auction/getAuction.getAuction
      FunctionName: getAuction
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: HTTP get method to get one item by id from a DynamoDB table.
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AuctionsTable
      Environment:
        Variables:
          AUCTIONS_TABLE_NAME: !Ref AuctionsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /auction/{id}
            Method: GET

  # This is a Lambda function config associated with the source code: createAuction.js
  createAuction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/auction/createAuction.createAuction
      FunctionName: createAuction
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref AuctionsTable
      Environment:
        Variables:
          AUCTIONS_TABLE_NAME: !Ref AuctionsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /auction
            Method: POST

  AuctionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AuctionTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema: # Required
        - AttributeName: id
          KeyType: HASH

Outputs:
  WebEndpoint:
    Description: 'API Gateway endpoint URL for Prod stage'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
